/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Consultas;

/**
 *
 * @author SENA
 */
import java.awt.EventQueue;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class ConsultaBD extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaBD
     */
    public ConsultaBD() {
            initComponents();
        cargarDriver();
    }
    private void cargarDriver() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        }catch(ClassNotFoundException ex) {
            setTitle(ex.toString());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Lbldescripcion = new javax.swing.JLabel();
        Lblprecio = new javax.swing.JLabel();
        Lblresultado = new javax.swing.JLabel();
        Tf1 = new javax.swing.JTextField();
        Tf2 = new javax.swing.JTextField();
        BtnAlta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(null);

        Lbldescripcion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Lbldescripcion.setForeground(new java.awt.Color(255, 255, 255));
        Lbldescripcion.setText("DESCRIPCION");
        jPanel1.add(Lbldescripcion);
        Lbldescripcion.setBounds(80, 110, 91, 20);

        Lblprecio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Lblprecio.setForeground(new java.awt.Color(255, 255, 255));
        Lblprecio.setText("PRECIO");
        jPanel1.add(Lblprecio);
        Lblprecio.setBounds(110, 170, 49, 20);

        Lblresultado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Lblresultado.setForeground(new java.awt.Color(255, 255, 255));
        Lblresultado.setText("RESULTADO");
        jPanel1.add(Lblresultado);
        Lblresultado.setBounds(150, 270, 80, 20);
        jPanel1.add(Tf1);
        Tf1.setBounds(180, 100, 190, 40);

        Tf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf2ActionPerformed(evt);
            }
        });
        jPanel1.add(Tf2);
        Tf2.setBounds(180, 160, 190, 40);

        BtnAlta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnAlta.setText("ALTAS");
        BtnAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAltaActionPerformed(evt);
            }
        });
        jPanel1.add(BtnAlta);
        BtnAlta.setBounds(250, 340, 73, 26);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Tf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tf2ActionPerformed

    private void BtnAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAltaActionPerformed
        // TODO add your handling code here:
        BtnAlta.addActionListener(new ActionListener() {
    public void actionPerformed(ActionEvent arg0) {


        Lblresultado.setText("");
        try {
            try (Connection conexion = DriverManager.getConnection("jdbc:mysql://localhost/base2","root","")) {
                Statement comando=conexion.createStatement();
                comando.executeUpdate("insert into articulos(descripcion,precio) values('"+Tf1.getText()+"',"+Tf2.getText()+")");

            conexion.close();
            }


        Lblresultado.setText("se registraron los datos");

        Tf1.setText("");
        Tf2.setText("");
        } catch(SQLException ex){
        setTitle(ex.toString());
        }
        }
        });

    }//GEN-LAST:event_BtnAltaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaBD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAlta;
    private javax.swing.JLabel Lbldescripcion;
    private javax.swing.JLabel Lblprecio;
    private javax.swing.JLabel Lblresultado;
    private javax.swing.JTextField Tf1;
    private javax.swing.JTextField Tf2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
